#cloudbuild.yaml
steps:
  - name: 'docker/compose:1.22.0'
    args: ['up', '-d']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'workspace_app:latest', 'gcr.io/${PROJECT_ID}/${REPO_NAME}__app:${COMMIT_SHA}']
  - name: 'ubuntu'
    args: ['bash', 'deploy.sh']
images:
  - 'gcr.io/${PROJECT_ID}/${REPO_NAME}__app:${COMMIT_SHA}'
timeout: 1200s
