#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Feb 13 17:09:28 2019

@author: cliffk
"""

import sciris as sc
import hiptool as hp

gbddatafile = 'gbd-data.dat'

def getcountryburden(country):
    ''' Load the burden from a given country '''
    
    # Load data
    try:
        datadir = hp.HPpath('data')
        datafile = sc.loadobj(datadir+gbddatafile)
        countryburden = datafile[country]
    except Exception as E:
        errormsg = 'Could not load data for "%s"; not found as a file or country: %s' % (country, str(E))
        raise Exception(errormsg)
    
    # Error checking -- WARNING, could be improved!
    try:
        burdenkeys = countryburden.keys()
        assert 'DALY'       in burdenkeys[0]
        assert 'Death'      in burdenkeys[1]
        assert 'Prevalence' in burdenkeys[2]
    except Exception as E:
        errormsg = 'Keys DALYs, deaths, and prevalence not in right order: %s (%s)' % (burdenkeys, str(E))
        raise Exception(errormsg)
    return countryburden


def burdenhierarchy(key1, key2):
    ''' Determine the relationship between two keys '''
    
    # Process
    k1parts = key1.split('.')
    k2parts = key2.split('.')
    nk1 = len(k1parts)
    nk2 = len(k2parts)
    
    # Handle all causes -- 'T'
    if key1 == 'T':
        k1parts = []
        nk1 = 0
    if key2 == 'T':
        k2parts = []
        nk2 = 0
    
    # Handle everything else
    if key1 == key2:
        output = 'same'
    elif nk1 == nk2:
        output = 'none'
    elif nk1<nk2:
        if k1parts[:nk1] == k2parts[:nk1]: output = 'child'
        else:                              output = 'none'
    elif nk2<nk1:
        if k1parts[:nk2] == k2parts[:nk2]: output = 'parent'
        else:                              output = 'none'
    else:
        raise Exception(f'Relationship not determined: {key1} vs {key2}')
    leveldiff = abs(nk1-nk2)
    if output in ['child', 'parent'] and leveldiff>1:
        output += f'-{leveldiff}'
    return output


countrylist = [
 'Afghanistan',
 'Albania',
 'Algeria',
 'American Samoa',
 'Andorra',
 'Angola',
 'Antigua and Barbuda',
 'Argentina',
 'Armenia',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahrain',
 'Bangladesh',
 'Barbados',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bermuda',
 'Bhutan',
 'Bolivia',
 'Bosnia and Herzegovina',
 'Botswana',
 'Brazil',
 'Brunei',
 'Bulgaria',
 'Burkina Faso',
 'Burundi',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Cape Verde',
 'Central African Republic',
 'Chad',
 'Chile',
 'China',
 'Colombia',
 'Comoros',
 'Congo',
 'Costa Rica',
 "Cote d'Ivoire",
 'Croatia',
 'Cuba',
 'Cyprus',
 'Czech Republic',
 'Democratic Republic of the Congo',
 'Denmark',
 'Djibouti',
 'Dominica',
 'Dominican Republic',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'Equatorial Guinea',
 'Eritrea',
 'Estonia',
 'Ethiopia',
 'Federated States of Micronesia',
 'Fiji',
 'Finland',
 'France',
 'Gabon',
 'Georgia',
 'Germany',
 'Ghana',
 'Greece',
 'Greenland',
 'Grenada',
 'Guam',
 'Guatemala',
 'Guinea',
 'Guinea-Bissau',
 'Guyana',
 'Haiti',
 'Honduras',
 'Hungary',
 'Iceland',
 'India',
 'Indonesia',
 'Iran',
 'Iraq',
 'Ireland',
 'Israel',
 'Italy',
 'Jamaica',
 'Japan',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Kiribati',
 'Kuwait',
 'Kyrgyzstan',
 'Laos',
 'Latvia',
 'Lebanon',
 'Lesotho',
 'Liberia',
 'Libya',
 'Lithuania',
 'Luxembourg',
 'Macedonia',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Maldives',
 'Mali',
 'Malta',
 'Marshall Islands',
 'Mauritania',
 'Mauritius',
 'Mexico',
 'Moldova',
 'Mongolia',
 'Montenegro',
 'Morocco',
 'Mozambique',
 'Myanmar',
 'Namibia',
 'Nepal',
 'Netherlands',
 'New Zealand',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'North Korea',
 'Northern Mariana Islands',
 'Norway',
 'Oman',
 'Pakistan',
 'Palestine',
 'Panama',
 'Papua New Guinea',
 'Paraguay',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Puerto Rico',
 'Qatar',
 'Romania',
 'Russian Federation',
 'Rwanda',
 'Saint Lucia',
 'Saint Vincent and the Grenadines',
 'Samoa',
 'Sao Tome and Principe',
 'Saudi Arabia',
 'Senegal',
 'Serbia',
 'Seychelles',
 'Sierra Leone',
 'Singapore',
 'Slovakia',
 'Slovenia',
 'Solomon Islands',
 'Somalia',
 'South Africa',
 'South Korea',
 'South Sudan',
 'Spain',
 'Sri Lanka',
 'Sudan',
 'Suriname',
 'Swaziland',
 'Sweden',
 'Switzerland',
 'Syria',
 'Taiwan',
 'Tajikistan',
 'Tanzania',
 'Thailand',
 'The Bahamas',
 'The Gambia',
 'Timor-Leste',
 'Togo',
 'Tonga',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkey',
 'Turkmenistan',
 'Uganda',
 'Ukraine',
 'United Arab Emirates',
 'United Kingdom',
 'United States',
 'Uruguay',
 'Uzbekistan',
 'Vanuatu',
 'Venezuela',
 'Vietnam',
 'Virgin Islands, U.S.',
 'Yemen',
 'Zambia',
 'Zimbabwe',
]

burdeninfo = sc.objdict()

burdeninfo.dict = sc.odict([
('A', 'Communicable, maternal, neonatal, and nutritional diseases'),
('A.1', 'HIV/AIDS and sexually transmitted infections'),
('A.1.1', 'HIV/AIDS'),
('A.1.1.1', 'HIV/AIDS - Drug-susceptible Tuberculosis'),
('A.1.1.2', 'HIV/AIDS - Multidrug-resistant Tuberculosis without extensive drug resistance'),
('A.1.1.3', 'HIV/AIDS - Extensively drug-resistant Tuberculosis'),
('A.1.1.4', 'HIV/AIDS resulting in other diseases'),
('A.1.2', 'Sexually transmitted infections excluding HIV'),
('A.1.2.1', 'Syphilis'),
('A.1.2.2', 'Chlamydial infection'),
('A.1.2.3', 'Gonococcal infection'),
('A.1.2.4', 'Trichomoniasis'),
('A.1.2.5', 'Genital herpes'),
('A.1.2.6', 'Other sexually transmitted infections'),
('A.2', 'Respiratory infections and tuberculosis'),
('A.2.1', 'Tuberculosis'),
('A.2.1.1', 'Latent tuberculosis infection'),
('A.2.1.2', 'Drug-susceptible tuberculosis'),
('A.2.1.3', 'Multidrug-resistant tuberculosis without extensive drug resistance'),
('A.2.1.4', 'Extensively drug-resistant tuberculosis'),
('A.2.2', 'Lower respiratory infections'),
('A.2.3', 'Upper respiratory infections'),
('A.2.4', 'Otitis media'),
('A.3', 'Enteric infections'),
('A.3.1', 'Diarrheal diseases'),
('A.3.2', 'Typhoid and paratyphoid'),
('A.3.2.1', 'Typhoid fever'),
('A.3.2.2', 'Paratyphoid fever'),
('A.3.3', 'Invasive Non-typhoidal Salmonella (iNTS)'),
('A.3.4', 'Other intestinal infectious diseases'),
('A.4', 'Neglected tropical diseases and malaria'),
('A.4.1', 'Malaria'),
('A.4.10', 'Trachoma'),
('A.4.11', 'Dengue'),
('A.4.12', 'Yellow fever'),
('A.4.13', 'Rabies'),
('A.4.14', 'Intestinal nematode infections'),
('A.4.14.1', 'Ascariasis'),
('A.4.14.2', 'Trichuriasis'),
('A.4.14.3', 'Hookworm disease'),
('A.4.15', 'Food-borne trematodiases'),
('A.4.16', 'Leprosy'),
('A.4.17', 'Ebola'),
('A.4.18', 'Zika virus'),
('A.4.19', 'Guinea worm disease'),
('A.4.2', 'Chagas disease'),
('A.4.20', 'Other neglected tropical diseases'),
('A.4.3', 'Leishmaniasis'),
('A.4.3.1', 'Visceral leishmaniasis'),
('A.4.3.2', 'Cutaneous and mucocutaneous leishmaniasis'),
('A.4.4', 'African trypanosomiasis'),
('A.4.5', 'Schistosomiasis'),
('A.4.6', 'Cysticercosis'),
('A.4.7', 'Cystic echinococcosis'),
('A.4.8', 'Lymphatic filariasis'),
('A.4.9', 'Onchocerciasis'),
('A.5', 'Other infectious diseases'),
('A.5.1', 'Meningitis'),
('A.5.1.1', 'Pneumococcal meningitis'),
('A.5.1.2', 'H influenzae type B meningitis'),
('A.5.1.3', 'Meningococcal meningitis'),
('A.5.1.4', 'Other meningitis'),
('A.5.2', 'Encephalitis'),
('A.5.3', 'Diphtheria'),
('A.5.4', 'Whooping cough'),
('A.5.5', 'Tetanus'),
('A.5.6', 'Measles'),
('A.5.7', 'Varicella and herpes zoster'),
('A.5.8', 'Acute hepatitis'),
('A.5.8.1', 'Acute hepatitis A'),
('A.5.8.2', 'Acute hepatitis B'),
('A.5.8.3', 'Acute hepatitis C'),
('A.5.8.4', 'Acute hepatitis E'),
('A.5.9', 'Other unspecified infectious diseases'),
('A.6', 'Maternal and neonatal disorders'),
('A.6.1', 'Maternal disorders'),
('A.6.1.1', 'Maternal hemorrhage'),
('A.6.1.10', 'Other maternal disorders'),
('A.6.1.2', 'Maternal sepsis and other maternal infections'),
('A.6.1.3', 'Maternal hypertensive disorders'),
('A.6.1.4', 'Maternal obstructed labor and uterine rupture'),
('A.6.1.5', 'Maternal abortion and miscarriage'),
('A.6.1.6', 'Ectopic pregnancy'),
('A.6.1.7', 'Indirect maternal deaths'),
('A.6.1.8', 'Late maternal deaths'),
('A.6.1.9', 'Maternal deaths aggravated by HIV/AIDS'),
('A.6.2', 'Neonatal disorders'),
('A.6.2.1', 'Neonatal preterm birth'),
('A.6.2.2', 'Neonatal encephalopathy due to birth asphyxia and trauma'),
('A.6.2.3', 'Neonatal sepsis and other neonatal infections'),
('A.6.2.4', 'Hemolytic disease and other neonatal jaundice'),
('A.6.2.5', 'Other neonatal disorders'),
('A.7', 'Nutritional deficiencies'),
('A.7.1', 'Protein-energy malnutrition'),
('A.7.2', 'Iodine deficiency'),
('A.7.3', 'Vitamin A deficiency'),
('A.7.4', 'Dietary iron deficiency'),
('A.7.5', 'Other nutritional deficiencies'),
('B', 'Non-communicable diseases'),
('B.1', 'Neoplasms'),
('B.1.1', 'Lip and oral cavity cancer'),
('B.1.10', 'Larynx cancer'),
('B.1.11', 'Tracheal, bronchus, and lung cancer'),
('B.1.12', 'Malignant skin melanoma'),
('B.1.13', 'Non-melanoma skin cancer'),
('B.1.13.1', 'Non-melanoma skin cancer (squamous-cell carcinoma)'),
('B.1.13.2', 'Non-melanoma skin cancer (basal-cell carcinoma)'),
('B.1.14', 'Breast cancer'),
('B.1.15', 'Cervical cancer'),
('B.1.16', 'Uterine cancer'),
('B.1.17', 'Ovarian cancer'),
('B.1.18', 'Prostate cancer'),
('B.1.19', 'Testicular cancer'),
('B.1.2', 'Nasopharynx cancer'),
('B.1.20', 'Kidney cancer'),
('B.1.21', 'Bladder cancer'),
('B.1.22', 'Brain and nervous system cancer'),
('B.1.23', 'Thyroid cancer'),
('B.1.24', 'Mesothelioma'),
('B.1.25', 'Hodgkin lymphoma'),
('B.1.26', 'Non-Hodgkin lymphoma'),
('B.1.27', 'Multiple myeloma'),
('B.1.28', 'Leukemia'),
('B.1.28.1', 'Acute lymphoid leukemia'),
('B.1.28.2', 'Chronic lymphoid leukemia'),
('B.1.28.3', 'Acute myeloid leukemia'),
('B.1.28.4', 'Chronic myeloid leukemia'),
('B.1.28.5', 'Other leukemia'),
('B.1.29', 'Other malignant neoplasms'),
('B.1.3', 'Other pharynx cancer'),
('B.1.30', 'Other neoplasms'),
('B.1.30.1', 'Myelodysplastic, myeloproliferative, and other hematopoietic neoplasms'),
('B.1.30.2', 'Benign and in situ intestinal neoplasms'),
('B.1.30.3', 'Benign and in situ cervical and uterine neoplasms'),
('B.1.30.4', 'Other benign and in situ neoplasms'),
('B.1.4', 'Esophageal cancer'),
('B.1.5', 'Stomach cancer'),
('B.1.6', 'Colon and rectum cancer'),
('B.1.7', 'Liver cancer'),
('B.1.7.1', 'Liver cancer due to hepatitis B'),
('B.1.7.2', 'Liver cancer due to hepatitis C'),
('B.1.7.3', 'Liver cancer due to alcohol use'),
('B.1.7.4', 'Liver cancer due to NASH'),
('B.1.7.5', 'Liver cancer due to other causes'),
('B.1.8', 'Gallbladder and biliary tract cancer'),
('B.1.9', 'Pancreatic cancer'),
('B.10', 'Sense organ diseases'),
('B.10.1', 'Blindness and vision impairment'),
('B.10.1.1', 'Glaucoma'),
('B.10.1.2', 'Cataract'),
('B.10.1.3', 'Age-related macular degeneration'),
('B.10.1.4', 'Refraction disorders'),
('B.10.1.5', 'Near vision loss'),
('B.10.1.6', 'Other vision loss'),
('B.10.2', 'Age-related and other hearing loss'),
('B.10.3', 'Other sense organ diseases'),
('B.11', 'Musculoskeletal disorders'),
('B.11.1', 'Rheumatoid arthritis'),
('B.11.2', 'Osteoarthritis'),
('B.11.3', 'Low back pain'),
('B.11.4', 'Neck pain'),
('B.11.5', 'Gout'),
('B.11.6', 'Other musculoskeletal disorders'),
('B.12', 'Other non-communicable diseases'),
('B.12.1', 'Congenital birth defects'),
('B.12.1.1', 'Neural tube defects'),
('B.12.1.10', 'Digestive congenital anomalies'),
('B.12.1.11', 'Other congenital birth defects'),
('B.12.1.2', 'Congenital heart anomalies'),
('B.12.1.3', 'Orofacial clefts'),
('B.12.1.4', 'Down syndrome'),
('B.12.1.5', 'Turner syndrome'),
('B.12.1.6', 'Klinefelter syndrome'),
('B.12.1.7', 'Other chromosomal abnormalities'),
('B.12.1.8', 'Congenital musculoskeletal and limb anomalies'),
('B.12.1.9', 'Urogenital congenital anomalies'),
('B.12.2', 'Urinary diseases and male infertility'),
('B.12.2.1', 'Urinary tract infections'),
('B.12.2.2', 'Urolithiasis'),
('B.12.2.3', 'Benign prostatic hyperplasia'),
('B.12.2.4', 'Male infertility'),
('B.12.2.5', 'Other urinary diseases'),
('B.12.3', 'Gynecological diseases'),
('B.12.3.1', 'Uterine fibroids'),
('B.12.3.2', 'Polycystic ovarian syndrome'),
('B.12.3.3', 'Female infertility'),
('B.12.3.4', 'Endometriosis'),
('B.12.3.5', 'Genital prolapse'),
('B.12.3.6', 'Premenstrual syndrome'),
('B.12.3.7', 'Other gynecological diseases'),
('B.12.4', 'Hemoglobinopathies and hemolytic anemias'),
('B.12.4.1', 'Thalassemias'),
('B.12.4.2', 'Thalassemias trait'),
('B.12.4.3', 'Sickle cell disorders'),
('B.12.4.4', 'Sickle cell trait'),
('B.12.4.5', 'G6PD deficiency'),
('B.12.4.6', 'G6PD trait'),
('B.12.4.7', 'Other hemoglobinopathies and hemolytic anemias'),
('B.12.5', 'Endocrine, metabolic, blood, and immune disorders'),
('B.12.6', 'Oral disorders'),
('B.12.6.1', 'Caries of deciduous teeth'),
('B.12.6.2', 'Caries of permanent teeth'),
('B.12.6.3', 'Periodontal diseases'),
('B.12.6.4', 'Edentulism and severe tooth loss'),
('B.12.6.5', 'Other oral disorders'),
('B.12.7', 'Sudden infant death syndrome'),
('B.2', 'Cardiovascular diseases'),
('B.2.1', 'Rheumatic heart disease'),
('B.2.10', 'Endocarditis'),
('B.2.11', 'Other cardiovascular and circulatory diseases'),
('B.2.2', 'Ischemic heart disease'),
('B.2.3', 'Stroke'),
('B.2.3.1', 'Ischemic stroke'),
('B.2.3.2', 'Intracerebral hemorrhage'),
('B.2.3.3', 'Subarachnoid hemorrhage'),
('B.2.4', 'Hypertensive heart disease'),
('B.2.5', 'Non-rheumatic valvular heart disease'),
('B.2.5.1', 'Non-rheumatic calcific aortic valve disease'),
('B.2.5.2', 'Non-rheumatic degenerative mitral valve disease'),
('B.2.5.3', 'Other non-rheumatic valve diseases'),
('B.2.6', 'Cardiomyopathy and myocarditis'),
('B.2.6.1', 'Myocarditis'),
('B.2.6.2', 'Alcoholic cardiomyopathy'),
('B.2.6.3', 'Other cardiomyopathy'),
('B.2.7', 'Atrial fibrillation and flutter'),
('B.2.8', 'Aortic aneurysm'),
('B.2.9', 'Peripheral artery disease'),
('B.3', 'Chronic respiratory diseases'),
('B.3.1', 'Chronic obstructive pulmonary disease'),
('B.3.2', 'Pneumoconiosis'),
('B.3.2.1', 'Silicosis'),
('B.3.2.2', 'Asbestosis'),
('B.3.2.3', 'Coal workers pneumoconiosis'),
('B.3.2.4', 'Other pneumoconiosis'),
('B.3.3', 'Asthma'),
('B.3.4', 'Interstitial lung disease and pulmonary sarcoidosis'),
('B.3.5', 'Other chronic respiratory diseases'),
('B.4', 'Digestive diseases'),
('B.4.1', 'Cirrhosis and other chronic liver diseases'),
('B.4.1.1', 'Cirrhosis and other chronic liver diseases due to hepatitis B'),
('B.4.1.2', 'Cirrhosis and other chronic liver diseases due to hepatitis C'),
('B.4.1.3', 'Cirrhosis and other chronic liver diseases due to alcohol use'),
('B.4.1.4', 'Cirrhosis due to NASH'),
('B.4.1.5', 'Cirrhosis and other chronic liver diseases due to other causes'),
('B.4.10', 'Other digestive diseases'),
('B.4.2', 'Upper digestive system diseases'),
('B.4.2.1', 'Peptic ulcer disease'),
('B.4.2.2', 'Gastritis and duodenitis'),
('B.4.2.3', 'Gastroesophageal reflux disease'),
('B.4.3', 'Appendicitis'),
('B.4.4', 'Paralytic ileus and intestinal obstruction'),
('B.4.5', 'Inguinal, femoral, and abdominal hernia'),
('B.4.6', 'Inflammatory bowel disease'),
('B.4.7', 'Vascular intestinal disorders'),
('B.4.8', 'Gallbladder and biliary diseases'),
('B.4.9', 'Pancreatitis'),
('B.5', 'Neurological disorders'),
('B.5.1', "Alzheimer's disease and other dementias"),
('B.5.2', "Parkinson's disease"),
('B.5.3', 'Epilepsy'),
('B.5.4', 'Multiple sclerosis'),
('B.5.5', 'Motor neuron disease'),
('B.5.6', 'Headache disorders'),
('B.5.6.1', 'Migraine'),
('B.5.6.2', 'Tension-type headache'),
('B.5.7', 'Other neurological disorders'),
('B.6', 'Mental disorders'),
('B.6.1', 'Schizophrenia'),
('B.6.10', 'Other mental disorders'),
('B.6.2', 'Depressive disorders'),
('B.6.2.1', 'Major depressive disorder'),
('B.6.2.2', 'Dysthymia'),
('B.6.3', 'Bipolar disorder'),
('B.6.4', 'Anxiety disorders'),
('B.6.5', 'Eating disorders'),
('B.6.5.1', 'Anorexia nervosa'),
('B.6.5.2', 'Bulimia nervosa'),
('B.6.6', 'Autism spectrum disorders'),
('B.6.7', 'Attention-deficit/hyperactivity disorder'),
('B.6.8', 'Conduct disorder'),
('B.6.9', 'Idiopathic developmental intellectual disability'),
('B.7', 'Substance use disorders'),
('B.7.1', 'Alcohol use disorders'),
('B.7.2', 'Drug use disorders'),
('B.7.2.1', 'Opioid use disorders'),
('B.7.2.2', 'Cocaine use disorders'),
('B.7.2.3', 'Amphetamine use disorders'),
('B.7.2.4', 'Cannabis use disorders'),
('B.7.2.5', 'Other drug use disorders'),
('B.8', 'Diabetes and kidney diseases'),
('B.8.1', 'Diabetes mellitus'),
('B.8.1.1', 'Diabetes mellitus type 1'),
('B.8.1.2', 'Diabetes mellitus type 2'),
('B.8.2', 'Chronic kidney disease'),
('B.8.2.1', 'Chronic kidney disease due to diabetes mellitus type 1'),
('B.8.2.2', 'Chronic kidney disease due to diabetes mellitus type 2'),
('B.8.2.3', 'Chronic kidney disease due to hypertension'),
('B.8.2.4', 'Chronic kidney disease due to glomerulonephritis'),
('B.8.2.5', 'Chronic kidney disease due to other and unspecified causes'),
('B.8.3', 'Acute glomerulonephritis'),
('B.9', 'Skin and subcutaneous diseases'),
('B.9.1', 'Dermatitis'),
('B.9.1.1', 'Atopic dermatitis'),
('B.9.1.2', 'Contact dermatitis'),
('B.9.1.3', 'Seborrhoeic dermatitis'),
('B.9.10', 'Urticaria'),
('B.9.11', 'Decubitus ulcer'),
('B.9.12', 'Other skin and subcutaneous diseases'),
('B.9.2', 'Psoriasis'),
('B.9.3', 'Bacterial skin diseases'),
('B.9.3.1', 'Cellulitis'),
('B.9.3.2', 'Pyoderma'),
('B.9.4', 'Scabies'),
('B.9.5', 'Fungal skin diseases'),
('B.9.6', 'Viral skin diseases'),
('B.9.7', 'Acne vulgaris'),
('B.9.8', 'Alopecia areata'),
('B.9.9', 'Pruritus'),
('C', 'Injuries'),
('C.1', 'Transport injuries'),
('C.1.1', 'Road injuries'),
('C.1.1.1', 'Pedestrian road injuries'),
('C.1.1.2', 'Cyclist road injuries'),
('C.1.1.3', 'Motorcyclist road injuries'),
('C.1.1.4', 'Motor vehicle road injuries'),
('C.1.1.5', 'Other road injuries'),
('C.1.2', 'Other transport injuries'),
('C.2', 'Unintentional injuries'),
('C.2.1', 'Falls'),
('C.2.10', 'Exposure to forces of nature'),
('C.2.11', 'Other unintentional injuries'),
('C.2.2', 'Drowning'),
('C.2.3', 'Fire, heat, and hot substances'),
('C.2.4', 'Poisonings'),
('C.2.4.1', 'Poisoning by carbon monoxide'),
('C.2.4.2', 'Poisoning by other means'),
('C.2.5', 'Exposure to mechanical forces'),
('C.2.5.1', 'Unintentional firearm injuries'),
('C.2.5.2', 'Other exposure to mechanical forces'),
('C.2.6', 'Adverse effects of medical treatment'),
('C.2.7', 'Animal contact'),
('C.2.7.1', 'Venomous animal contact'),
('C.2.7.2', 'Non-venomous animal contact'),
('C.2.8', 'Foreign body'),
('C.2.8.1', 'Pulmonary aspiration and foreign body in airway'),
('C.2.8.2', 'Foreign body in eyes'),
('C.2.8.3', 'Foreign body in other body part'),
('C.2.9', 'Environmental heat and cold exposure'),
('C.3', 'Self-harm and interpersonal violence'),
('C.3.1', 'Self-harm'),
('C.3.1.1', 'Self-harm by firearm'),
('C.3.1.2', 'Self-harm by other specified means'),
('C.3.2', 'Interpersonal violence'),
('C.3.2.1', 'Physical violence by firearm'),
('C.3.2.2', 'Physical violence by sharp object'),
('C.3.2.3', 'Sexual violence'),
('C.3.2.4', 'Physical violence by other means'),
('C.3.3', 'Conflict and terrorism'),
('C.3.4', 'Executions and police conflict'),
('T', 'All causes')
])

burdeninfo.rdict = sc.odict([(key,val) for key,val in zip(burdeninfo.dict.values(), burdeninfo.dict.keys())]) # Reverse order of keys and values

# Parse into categories
keys = ['children', 'allchildren', 'parent', 'allparents', 'istwig']
for key in keys:
    burdeninfo[key] = sc.odict()
for code in burdeninfo.dict.keys():
    for key in keys:
        burdeninfo[key][code] = []
    for code2 in burdeninfo.dict.keys():
        relationship = burdenhierarchy(code, code2)
        
        if relationship == 'child':
            burdeninfo.children[code].append(code2)
        
        if 'child' in relationship:
            burdeninfo.allchildren[code].append(code2)
        
        if relationship == 'parent':
            burdeninfo.parent[code].append(code2)
        
        if 'parent' in relationship:
            burdeninfo.allparents[code].append(code2)
    
    if not burdeninfo.children[code]:
        burdeninfo.istwig[code] = True
    else:
        burdeninfo.istwig[code] = False
    